// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TABTest
{
	public partial class TabBarViewController : UITabBarController
	{
		public TabBarViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
