// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TABTest
{
	public partial class ViewControllerTwo : UIViewController
	{
		public ViewControllerTwo (IntPtr handle) : base (handle)
		{
		}
	}
}
