// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TABTest
{
	public partial class ViewControllerOne : UIViewController
	{
		public ViewControllerOne (IntPtr handle) : base (handle)
		{
		}
	}
}
